debug: True

server:
    port: 8010
    log_path: logs
    run_path: run

database_url: 'mysql+mysqldb://remote_user:remote_passwd@10.10.50.30/publish?charset=utf8'

database_config:
    encoding: utf8
    pool_recycle: 3600
    echo : False
    pool_size: 10

token_secret: token_secret

ldap:
    ldap_server: 192.168.1.96
    baseDN: ou=研发部,ou=产研中心,ou=User,dc=yunnex,dc=com
    port: 389
    user: cn=devops,ou=运维,ou=运维工程部,ou=研发部,ou=产研中心,ou=User,dc=yunnex,dc=com
    password: GRjPXl1bm5

ansible:
    module_path: '/data/env/python36publish-server/lib/python3.6/site-packages/ansible/modules'

sh_path: /data/web/publish-server/sh

project_root_path: /home/data/project
cmdb_server:
    url: http://cmdb.ops.yunnex.com/api
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImRldm9wcyIsImVtYWlsIjoiZGV2b3BzQHl1bm5leC5jb20iLCJwaG9uZSI6IjE4MTg4NjE2MTA2IiwiZnVsbG5hbWUiOiJkZXZvcHMiLCJkZXBhcnRtZW50X25hbWUiOlsiXHU4ZmQwXHU3ZWY0XHU1ZGU1XHU3YTBiXHU5MGU4Il19.FIDqQxcq2EePLZ-MNeOqqTk7qQ84uXcgvq39RQfpW1w

package_source_url: http://10.10.50.30/project

# 特殊的mod，同时需要操作nginx
special_mod_name:
    - order-mod-facade
    - cashier-mod-service
    - saofu-mod-broker
    - saofu-mod-ditui
    - yunnex-mod-foundation
    - mall-mod-cart
    - open-mod-api
    - marketing
    - canyin
    - waimai

dubbo_admin:
    authkey: 'yunnex'
    yunnex_admin_url: 'http://192.168.1.88:8020/yunnex-admin'
    error_name:
        promotion-mod-job: promotion-app-scheduler
        user-mod-card: promotion-mod-card
        promotion-api-pos: saofu-client
        shop-api-pos: saofu-client
        stats: saofu-monitor-web
        user-web-mobile: user-mobile-web
        wxapp-web-api: wxapp-web

    origin_name:
       - marketing
       - canyin
       - waimai
