debug: True

server:
    port: 8010
    log_path: logs
    run_path: run

database_url: 'mysql+mysqldb://remote_user:remote_passwd@10.10.50.30/publish?charset=utf8'

database_config:
    encoding: utf8
    pool_recycle: 3600
    echo : False
    pool_size: 10

token_secret: token_secret

ldap:
    ldap_server: 192.168.1.96
    baseDN: ou=研发部,ou=产研中心,ou=User,dc=yunnex,dc=com
    port: 389
    user: cn=devops,ou=运维,ou=运维工程部,ou=研发部,ou=产研中心,ou=User,dc=yunnex,dc=com
    password: GRjPXl1bm5

ansible:
    module_path: '/data/env/python36publish-server/lib/python3.6/site-packages/ansible/modules'

sh_path: /data/web/publish-server/sh
remote_sh_path: /data/sh
download_package_path: /home/data/project/release
inventory: /home/data/project/inventory
cmdb_server:
    url: http://cmdb.ops.yunnex.com/api
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImRldm9wcyIsImVtYWlsIjoiZGV2b3BzQHl1bm5leC5jb20iLCJwaG9uZSI6IjE4MTg4NjE2MTA2IiwiZnVsbG5hbWUiOiJkZXZvcHMiLCJkZXBhcnRtZW50X25hbWUiOlsiXHU4ZmQwXHU3ZWY0XHU1ZGU1XHU3YTBiXHU5MGU4Il19.FIDqQxcq2EePLZ-MNeOqqTk7qQ84uXcgvq39RQfpW1w

